
services:
  db:
    image: postgres:16-alpine
    container_name: sisc-postgres
    restart: always
    environment:
      POSTGRES_USER: sisc_user
      POSTGRES_PASSWORD: sisc_password
      POSTGRES_DB: sisc_db
    ports:
      - "5433:5432"
    volumes:
      - sisc-postgres-data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 128M

volumes:
  sisc-postgres-data:
