CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "full_name" varchar,
  "email" varchar UNIQUE,
  "password" varchar,
  "role" varchar,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "provinces" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar UNIQUE
);

CREATE TABLE "cities" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "province_id" integer,
  "name" varchar
);

CREATE TABLE "categories" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "slug" varchar UNIQUE
);

CREATE TABLE "events" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "organizer_id" integer,
  "category_id" integer,
  "city_id" integer,
  "title" varchar,
  "slug" varchar UNIQUE,
  "description" text,
  "banner_url" varchar,
  "event_date" timestamp,
  "location_detail" text,
  "external_link" varchar,
  "status" varchar DEFAULT 'pending',
  "is_scraped" boolean DEFAULT false,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp
);

CREATE TABLE "bookmarks" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer,
  "event_id" integer,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "notifications" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer,
  "title" varchar,
  "message" text,
  "is_read" boolean DEFAULT false,
  "created_at" timestamp DEFAULT (now())
);

COMMENT ON COLUMN "users"."role" IS 'admin, organizer, visitor';

COMMENT ON COLUMN "categories"."name" IS 'IT, Medis, Ekonomi, dll';

COMMENT ON COLUMN "events"."location_detail" IS 'Alamat spesifik/nama gedung';

COMMENT ON COLUMN "events"."external_link" IS 'Link pendaftaran asli';

COMMENT ON COLUMN "events"."status" IS 'pending, published, rejected, unpublish_request';

ALTER TABLE "cities" ADD FOREIGN KEY ("province_id") REFERENCES "provinces" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "events" ADD FOREIGN KEY ("organizer_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "events" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "events" ADD FOREIGN KEY ("city_id") REFERENCES "cities" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "bookmarks" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "bookmarks" ADD FOREIGN KEY ("event_id") REFERENCES "events" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "notifications" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;
