ALTER TABLE "event" ALTER COLUMN "judul" SET DATA TYPE varchar(255);--> statement-breakpoint
ALTER TABLE "event" ALTER COLUMN "slug" SET DATA TYPE varchar(255);--> statement-breakpoint
ALTER TABLE "event" ALTER COLUMN "banner_url" SET DATA TYPE varchar(512);--> statement-breakpoint
ALTER TABLE "event" ALTER COLUMN "penyelenggara" SET DATA TYPE varchar(255);--> statement-breakpoint
ALTER TABLE "event" ALTER COLUMN "link_eksternal" SET DATA TYPE varchar(512);--> statement-breakpoint
ALTER TABLE "event" ALTER COLUMN "nama_kontak" SET DATA TYPE varchar(255);--> statement-breakpoint
ALTER TABLE "event" ALTER COLUMN "email_kontak" SET DATA TYPE varchar(255);--> statement-breakpoint
ALTER TABLE "event" ALTER COLUMN "telepon_kontak" SET DATA TYPE varchar(20);--> statement-breakpoint
ALTER TABLE "event" ALTER COLUMN "website_sumber" SET DATA TYPE varchar(255);--> statement-breakpoint
ALTER TABLE "kategori" ALTER COLUMN "nama" SET DATA TYPE varchar(100);--> statement-breakpoint
ALTER TABLE "kategori" ALTER COLUMN "slug" SET DATA TYPE varchar(100);--> statement-breakpoint
ALTER TABLE "kategori" ALTER COLUMN "icon_url" SET DATA TYPE varchar(512);--> statement-breakpoint
ALTER TABLE "kota" ALTER COLUMN "nama" SET DATA TYPE varchar(100);--> statement-breakpoint
ALTER TABLE "lampiran_event" ALTER COLUMN "file_url" SET DATA TYPE varchar(512);--> statement-breakpoint
ALTER TABLE "lampiran_event" ALTER COLUMN "tipe_file" SET DATA TYPE varchar(50);--> statement-breakpoint
ALTER TABLE "log_admin" ALTER COLUMN "aksi" SET DATA TYPE varchar(100);--> statement-breakpoint
ALTER TABLE "pembicara_event" ALTER COLUMN "nama" SET DATA TYPE varchar(255);--> statement-breakpoint
ALTER TABLE "pembicara_event" ALTER COLUMN "peran" SET DATA TYPE varchar(100);--> statement-breakpoint
ALTER TABLE "pembicara_event" ALTER COLUMN "foto_url" SET DATA TYPE varchar(512);--> statement-breakpoint
ALTER TABLE "peserta" ALTER COLUMN "kode_peserta" SET DATA TYPE varchar(50);--> statement-breakpoint
ALTER TABLE "peserta" ALTER COLUMN "nama_lengkap" SET DATA TYPE varchar(255);--> statement-breakpoint
ALTER TABLE "peserta" ALTER COLUMN "email" SET DATA TYPE varchar(255);--> statement-breakpoint
ALTER TABLE "peserta" ALTER COLUMN "nomor_telepon" SET DATA TYPE varchar(20);--> statement-breakpoint
ALTER TABLE "peserta" ALTER COLUMN "jenis_kelamin" SET DATA TYPE varchar(20);--> statement-breakpoint
ALTER TABLE "profil_penyelenggara" ALTER COLUMN "nama_instansi" SET DATA TYPE varchar(255);--> statement-breakpoint
ALTER TABLE "profil_penyelenggara" ALTER COLUMN "dokumen_legalitas_url" SET DATA TYPE varchar(512);--> statement-breakpoint
ALTER TABLE "profil_penyelenggara" ALTER COLUMN "website_url" SET DATA TYPE varchar(255);--> statement-breakpoint
ALTER TABLE "provinsi" ALTER COLUMN "nama" SET DATA TYPE varchar(100);--> statement-breakpoint
ALTER TABLE "tag" ALTER COLUMN "nama" SET DATA TYPE varchar(100);--> statement-breakpoint
ALTER TABLE "transaksi" ALTER COLUMN "kode_booking" SET DATA TYPE varchar(50);--> statement-breakpoint
ALTER TABLE "transaksi" ALTER COLUMN "metode_pembayaran" SET DATA TYPE varchar(50);--> statement-breakpoint
ALTER TABLE "transaksi" ALTER COLUMN "bukti_pembayaran_url" SET DATA TYPE varchar(512);--> statement-breakpoint
ALTER TABLE "transaksi" ALTER COLUMN "status" SET DATA TYPE varchar(50);--> statement-breakpoint
ALTER TABLE "transaksi" ALTER COLUMN "status" SET DEFAULT 'pending';--> statement-breakpoint
ALTER TABLE "user_event" ALTER COLUMN "status" SET DATA TYPE varchar(50);--> statement-breakpoint
ALTER TABLE "users" ALTER COLUMN "nama_lengkap" SET DATA TYPE varchar(255);--> statement-breakpoint
ALTER TABLE "users" ALTER COLUMN "email" SET DATA TYPE varchar(255);--> statement-breakpoint
ALTER TABLE "users" ALTER COLUMN "nomor_telepon" SET DATA TYPE varchar(20);--> statement-breakpoint
ALTER TABLE "users" ALTER COLUMN "institution" SET DATA TYPE varchar(255);--> statement-breakpoint
ALTER TABLE "users" ALTER COLUMN "password" SET DATA TYPE varchar(255);--> statement-breakpoint
ALTER TABLE "users" ALTER COLUMN "jenis_kelamin" SET DATA TYPE varchar(20);--> statement-breakpoint
ALTER TABLE "users" ALTER COLUMN "nik" SET DATA TYPE varchar(16);--> statement-breakpoint
ALTER TABLE "users" ALTER COLUMN "role" SET DATA TYPE varchar(50);--> statement-breakpoint
ALTER TABLE "users" ALTER COLUMN "avatar_url" SET DATA TYPE varchar(512);--> statement-breakpoint
ALTER TABLE "users" ALTER COLUMN "avatar_url" SET DEFAULT '/uploads/avatars/fotodummy.jpg';