import { db } from "./index";
import { event } from "./schema";
import { SEED } from "@/lib/constants";

function slug(text: string) {
  return text.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
}

function futureDate(daysFromNow: number) {
  return new Date(Date.now() + daysFromNow * 86400000);
}

const DEFAULT_TERMS = `1. Peserta wajib melakukan registrasi melalui website SISC.
2. Peserta diharapkan hadir 15 menit sebelum acara dimulai untuk proses check-in.
3. Wajib menunjukkan E-Ticket (QR Code) saat memasuki area acara.
4. Menggunakan pakaian yang rapi, sopan, dan sesuai dengan tema acara.
5. Peserta wajib menjaga ketertiban dan kebersihan selama acara berlangsung.
6. Dilarang membawa senjata tajam, obat-obatan terlarang, atau benda berbahaya lainnya.
7. Panitia berhak membatalkan keikutsertaan jika peserta melanggar aturan yang ditetapkan.
8. Keputusan panitia bersifat mutlak dan tidak dapat diganggu gugat.`;

export async function seedEvents() {
  console.log("🚀 Redesigning and seeding 24 balanced events (12 Seminars, 12 Conferences, 12 Polines, 12 Umum)...");

  const events = [
    // === SEMINARS + POLINES (6 Events) ===
    { 
      id: 1, 
      organizerId: 2, 
      kategoriId: 1, 
      kotaId: 2, 
      judul: "Seminar Nasional AI & Big Data 2026", 
      jenisEvent: "seminar", 
      tipePlatform: "offline", 
      tipeHarga: "free", 
      harga: 0, 
      isEventPolines: true, 
      status: "published", 
      kuota: 200, 
      bannerUrl: "/uploads/banners/banner1.jpg", 
      syaratDanKetentuan: DEFAULT_TERMS, 
      deskripsi: "Seminar nasional membahas perkembangan kecerdasan buatan dan pengolahan data skala besar di Indonesia.", 
      detailLokasi: "Gedung Kuliah Bersama, Polines, Semarang", 
      tanggalMulai: futureDate(30), 
      tanggalSelesai: futureDate(30), 
      batasRegistrasi: futureDate(28), 
      namaKontak: "Panitia AI Polines", 
      emailKontak: "ai@polines.ac.id", 
      teleponKontak: "024-7473417", 
      jumlahTayangan: 245, 
      namaPembicara: "Dr. Eng. Ahmad Zaki", 
      peranPembicara: "AI Researcher at Google", 
      fotoPembicaraUrl: "/uploads/speakers/speaker1.jpg" 
    },
    { 
      id: 11, 
      organizerId: 2, 
      kategoriId: 9, 
      kotaId: 2, 
      judul: "Seminar Manajemen E-Sports Polines", 
      jenisEvent: "seminar", 
      tipePlatform: "offline", 
      tipeHarga: "paid", 
      harga: 30000, 
      isEventPolines: true, 
      status: "published", 
      kuota: 80, 
      bannerUrl: "/uploads/banners/banner11.jpg", 
      syaratDanKetentuan: DEFAULT_TERMS, 
      deskripsi: "Seminar industri E-Sports mengenai taktik manajemen turnamen dan karir profesional di kampus.", 
      detailLokasi: "GOR Polines, Semarang", 
      tanggalMulai: futureDate(10), 
      tanggalSelesai: futureDate(11), 
      batasRegistrasi: futureDate(7), 
      namaKontak: "UKM E-Sports", 
      emailKontak: "esports@polines.ac.id", 
      teleponKontak: "024-7473419", 
      jumlahTayangan: 498, 
      namaPembicara: "Jess No Limit", 
      peranPembicara: "E-Sports Professional", 
      fotoPembicaraUrl: "/uploads/speakers/speaker11.jpg" 
    },
    { 
      id: 16, 
      organizerId: 2, 
      kategoriId: 3, 
      kotaId: 2, 
      judul: "Seminar Seni Digital & UI/UX Polines", 
      jenisEvent: "seminar", 
      tipePlatform: "offline", 
      tipeHarga: "paid", 
      harga: 40000, 
      isEventPolines: true, 
      status: "published", 
      kuota: 150, 
      bannerUrl: "/uploads/banners/banner16.jpg", 
      syaratDanKetentuan: DEFAULT_TERMS, 
      deskripsi: "Integrasi seni digital dalam rancang bangun antarmuka pengguna yang estetik dan adaptif.", 
      detailLokasi: "Gedung Sate Creative Hub Polines, Semarang", 
      tanggalMulai: futureDate(25), 
      tanggalSelesai: futureDate(27), 
      batasRegistrasi: futureDate(22), 
      namaKontak: "Creative Hub Polines", 
      emailKontak: "creative@polines.ac.id", 
      teleponKontak: "024-7473420", 
      jumlahTayangan: 312, 
      namaPembicara: "Rio Purba", 
      peranPembicara: "UI/UX Designer & Mentor", 
      fotoPembicaraUrl: "/uploads/speakers/speaker16.jpg" 
    },
    { 
      id: 17, 
      organizerId: 2, 
      kategoriId: 1, 
      kotaId: 2, 
      judul: "Seminar Machine Learning Polines", 
      jenisEvent: "seminar", 
      tipePlatform: "online", 
      tipeHarga: "free", 
      harga: 0, 
      isEventPolines: true, 
      status: "published", 
      kuota: 500, 
      bannerUrl: "/uploads/banners/banner17.jpg", 
      syaratDanKetentuan: DEFAULT_TERMS, 
      deskripsi: "Pengenalan praktis dasar-dasar Machine Learning untuk mahasiswa dan dosen lingkungan Politeknik.", 
      detailLokasi: "Live Streaming YouTube & Zoom Polines", 
      tanggalMulai: futureDate(7), 
      tanggalSelesai: futureDate(7), 
      batasRegistrasi: futureDate(6), 
      namaKontak: "ML Hub Polines", 
      emailKontak: "ml@polines.ac.id", 
      teleponKontak: "081999888777", 
      jumlahTayangan: 721, 
      namaPembicara: "Andrew Ng", 
      peranPembicara: "AI Professor at Stanford", 
      fotoPembicaraUrl: "/uploads/speakers/speaker17.jpg" 
    },
    { 
      id: 19, 
      organizerId: 2, 
      kategoriId: 1, 
      kotaId: 2, 
      judul: "Seminar Riset Terapan Teknologi Elektro Polines", 
      jenisEvent: "seminar", 
      tipePlatform: "offline", 
      tipeHarga: "free", 
      harga: 0, 
      isEventPolines: true, 
      status: "published", 
      kuota: 120, 
      bannerUrl: "/uploads/banners/banner1.jpg", 
      syaratDanKetentuan: DEFAULT_TERMS, 
      deskripsi: "Seminar ilmiah hasil riset terapan bidang sistem kendali pintar dan energi terbarukan di elektro.", 
      detailLokasi: "Auditorium Direktorat Polines, Semarang", 
      tanggalMulai: futureDate(15), 
      tanggalSelesai: futureDate(15), 
      batasRegistrasi: futureDate(12), 
      namaKontak: "Himpunan Elektro", 
      emailKontak: "hmte@polines.ac.id", 
      teleponKontak: "024-7473421", 
      jumlahTayangan: 180, 
      namaPembicara: "Prof. Dr. Ir. Sunarno", 
      peranPembicara: "Electrical Engineering Specialist", 
      fotoPembicaraUrl: "/uploads/speakers/speaker1.jpg" 
    },
    { 
      id: 20, 
      organizerId: 2, 
      kategoriId: 2, 
      kotaId: 2, 
      judul: "Seminar Kewirausahaan Mahasiswa Polines", 
      jenisEvent: "seminar", 
      tipePlatform: "offline", 
      tipeHarga: "free", 
      harga: 0, 
      isEventPolines: true, 
      status: "published", 
      kuota: 250, 
      bannerUrl: "/uploads/banners/banner4.jpg", 
      syaratDanKetentuan: DEFAULT_TERMS, 
      deskripsi: "Menanamkan mental wirausaha berbasis teknologi (technopreneurship) untuk mahasiswa vokasi.", 
      detailLokasi: "Ruang Serbaguna Gedung C, Polines", 
      tanggalMulai: futureDate(22), 
      tanggalSelesai: futureDate(22), 
      batasRegistrasi: futureDate(20), 
      namaKontak: "Pusat Karir Polines", 
      emailKontak: "pusatkarir@polines.ac.id", 
      teleponKontak: "024-7473422", 
      jumlahTayangan: 310, 
      namaPembicara: "Dr. Sandiaga Uno", 
      peranPembicara: "Entrepreneur & Advisor", 
      fotoPembicaraUrl: "/uploads/speakers/speaker4.jpg" 
    },

    // === SEMINARS + UMUM (6 Events) ===
    { 
      id: 4, 
      organizerId: 2, 
      kategoriId: 2, 
      kotaId: null, 
      judul: "Webinar Kewirausahaan Muda", 
      jenisEvent: "seminar", 
      tipePlatform: "online", 
      tipeHarga: "free", 
      harga: 0, 
      isEventPolines: false, 
      status: "published", 
      kuota: 1000, 
      bannerUrl: "/uploads/banners/banner4.jpg", 
      syaratDanKetentuan: DEFAULT_TERMS, 
      deskripsi: "Webinar interaktif gratis bagi wirausahawan muda yang ingin merintis bisnis dari nol.", 
      detailLokasi: "Zoom Cloud Meetings & Youtube Live", 
      tanggalMulai: futureDate(14), 
      tanggalSelesai: futureDate(14), 
      batasRegistrasi: futureDate(13), 
      namaKontak: "Komunitas Wirausaha", 
      emailKontak: "wirausaha@gmail.com", 
      teleponKontak: "081234000111", 
      jumlahTayangan: 567, 
      linkEksternal: SEED.DEFAULT_TICKET_URL, 
      namaPembicara: "Gibran Rakabuming", 
      peranPembicara: "Entrepreneur & Mentor", 
      fotoPembicaraUrl: "/uploads/speakers/speaker4.jpg" 
    },
    { 
      id: 6, 
      organizerId: 2, 
      kategoriId: 6, 
      kotaId: 5, 
      judul: "Seminar Riset Pendidikan Inklusif", 
      jenisEvent: "seminar", 
      tipePlatform: "hybrid", 
      tipeHarga: "paid", 
      harga: 50000, 
      isEventPolines: false, 
      status: "published", 
      kuota: 150, 
      bannerUrl: "/uploads/banners/banner6.jpg", 
      syaratDanKetentuan: DEFAULT_TERMS, 
      deskripsi: "Seminar riset mendalam mengenai implementasi kurikulum inklusif di era pendidikan digital.", 
      detailLokasi: "Auditorium UGM, Yogyakarta", 
      tanggalMulai: futureDate(35), 
      tanggalSelesai: futureDate(35), 
      batasRegistrasi: futureDate(30), 
      namaKontak: "Forum Pendidikan", 
      emailKontak: "pendidikan@ugm.ac.id", 
      teleponKontak: "0274-513096", 
      jumlahTayangan: 120, 
      namaPembicara: "Anies Baswedan", 
      peranPembicara: "Education Consultant", 
      fotoPembicaraUrl: "/uploads/speakers/speaker6.jpg" 
    },
    { 
      id: 7, 
      organizerId: 2, 
      kategoriId: 7, 
      kotaId: 5, 
      judul: "Seminar Seni & Budaya Nusantara", 
      jenisEvent: "seminar", 
      tipePlatform: "offline", 
      tipeHarga: "paid", 
      harga: 25000, 
      isEventPolines: false, 
      status: "published", 
      kuota: 300, 
      bannerUrl: "/uploads/banners/banner7.jpg", 
      syaratDanKetentuan: DEFAULT_TERMS, 
      deskripsi: "Eksplorasi warisan seni nusantara dan diskusi panel pelestarian budaya daerah tradisional.", 
      detailLokasi: "Taman Budaya Yogyakarta", 
      tanggalMulai: futureDate(50), 
      tanggalSelesai: futureDate(52), 
      batasRegistrasi: futureDate(48), 
      namaKontak: "DKY Yogyakarta", 
      emailKontak: "senibudaya@jogja.go.id", 
      teleponKontak: "0274-523512", 
      jumlahTayangan: 210, 
      namaPembicara: "Didik Nini Thowok", 
      peranPembicara: "Cultural Expert", 
      fotoPembicaraUrl: "/uploads/speakers/speaker7.jpg" 
    },
    { 
      id: 10, 
      organizerId: 2, 
      kategoriId: 8, 
      kotaId: 10, 
      judul: "Seminar Gaya Hidup Berkelanjutan", 
      jenisEvent: "seminar", 
      tipePlatform: "hybrid", 
      tipeHarga: "free", 
      harga: 0, 
      isEventPolines: false, 
      status: "published", 
      kuota: 200, 
      bannerUrl: "/uploads/banners/banner10.jpg", 
      syaratDanKetentuan: DEFAULT_TERMS, 
      deskripsi: "Gerakan zero waste dan aksi nyata menjaga ekosistem bumi dari kehidupan sehari-hari.", 
      detailLokasi: "Bali Nusa Dua Convention Center", 
      tanggalMulai: futureDate(55), 
      tanggalSelesai: futureDate(55), 
      batasRegistrasi: futureDate(50), 
      namaKontak: "Green Foundation", 
      emailKontak: "green@bali.org", 
      teleponKontak: "0361-771234", 
      jumlahTayangan: 267, 
      namaPembicara: "Nadya Hutagalung", 
      peranPembicara: "Environmental Activist", 
      fotoPembicaraUrl: "/uploads/speakers/speaker10.jpg" 
    },
    { 
      id: 13, 
      organizerId: 2, 
      kategoriId: 4, 
      kotaId: 7, 
      judul: "Seminar Pendidikan Vokasi Nasional", 
      jenisEvent: "seminar", 
      tipePlatform: "offline", 
      tipeHarga: "free", 
      harga: 0, 
      isEventPolines: false, 
      status: "published", 
      kuota: 300, 
      bannerUrl: "/uploads/banners/banner13.jpg", 
      syaratDanKetentuan: DEFAULT_TERMS, 
      deskripsi: "Kolaborasi antara perguruan tinggi vokasi dengan kebutuhan spesifik industri modern.", 
      detailLokasi: "Hotel Claro Makassar", 
      tanggalMulai: futureDate(70), 
      tanggalSelesai: futureDate(72), 
      batasRegistrasi: futureDate(65), 
      namaKontak: "Forum Vokasi", 
      emailKontak: "vokasi@makassar.id", 
      teleponKontak: "0411-3621234", 
      jumlahTayangan: 98, 
      namaPembicara: "Nadiem Makarim", 
      peranPembicara: "Minister of Education", 
      fotoPembicaraUrl: "/uploads/speakers/speaker13.jpg" 
    },
    { 
      id: 15, 
      organizerId: 2, 
      kategoriId: 5, 
      kotaId: 8, 
      judul: "Seminar Kesehatan Masyarakat Palembang", 
      jenisEvent: "seminar", 
      tipePlatform: "offline", 
      tipeHarga: "free", 
      harga: 0, 
      isEventPolines: false, 
      status: "published", 
      kuota: 100, 
      bannerUrl: "/uploads/banners/banner15.jpg", 
      syaratDanKetentuan: DEFAULT_TERMS, 
      deskripsi: "Penyuluhan berkala mengenai pentingnya hidup sehat dan deteksi dini penyakit kronis.", 
      detailLokasi: "Puskesmas Kertapati, Palembang", 
      tanggalMulai: futureDate(15), 
      tanggalSelesai: futureDate(15), 
      batasRegistrasi: futureDate(12), 
      namaKontak: "Kesehatan Daerah", 
      emailKontak: "kes@palembang.go.id", 
      teleponKontak: "0711-3551234", 
      jumlahTayangan: 114, 
      namaPembicara: "dr. Tirta", 
      peranPembicara: "Health Influencer & Doctor", 
      fotoPembicaraUrl: "/uploads/speakers/speaker15.jpg" 
    },

    // === CONFERENCES + POLINES (6 Events) ===
    { 
      id: 5, 
      organizerId: 2, 
      kategoriId: 1, 
      kotaId: 2, 
      judul: "Konferensi Smart Campus Polines", 
      jenisEvent: "conference", 
      tipePlatform: "offline", 
      tipeHarga: "free", 
      harga: 0, 
      isEventPolines: true, 
      status: "published", 
      kuota: 100, 
      bannerUrl: "/uploads/banners/banner5.jpg", 
      syaratDanKetentuan: DEFAULT_TERMS, 
      deskripsi: "Konferensi hasil penelitian dan gagasan inovatif mengenai arsitektur sistem kampus cerdas terpadu.", 
      detailLokasi: "Lab Komputer Gedung A, Polines", 
      tanggalMulai: futureDate(21), 
      tanggalSelesai: futureDate(23), 
      batasRegistrasi: futureDate(18), 
      namaKontak: "BEM Polines", 
      emailKontak: "bem@polines.ac.id", 
      teleponKontak: "024-7473418", 
      jumlahTayangan: 234, 
      namaPembicara: "Prof. Sujatmiko", 
      peranPembicara: "IT Infrastructure Lead", 
      fotoPembicaraUrl: "/uploads/speakers/speaker5.jpg" 
    },
    { 
      id: 9, 
      organizerId: 2, 
      kategoriId: 4, 
      kotaId: 2, 
      judul: "Konferensi Sains & Teknologi Python Polines", 
      jenisEvent: "conference", 
      tipePlatform: "offline", 
      tipeHarga: "paid", 
      harga: 75000, 
      isEventPolines: true, 
      status: "published", 
      kuota: 60, 
      bannerUrl: "/uploads/banners/banner9.jpg", 
      syaratDanKetentuan: DEFAULT_TERMS, 
      deskripsi: "Pertemuan riset tingkat lanjut pemanfaatan ekosistem Python untuk sains komputasi dan matematika terapan.", 
      detailLokasi: "Gedung Kuliah Bersama Lantai 4, Polines", 
      tanggalMulai: futureDate(28), 
      tanggalSelesai: futureDate(29), 
      batasRegistrasi: futureDate(25), 
      namaKontak: "Python Club Polines", 
      emailKontak: "python@polines.ac.id", 
      teleponKontak: "024-7473423", 
      jumlahTayangan: 189, 
      namaPembicara: "Guido van Rossum", 
      peranPembicara: "Python Language Creator", 
      fotoPembicaraUrl: "/uploads/speakers/speaker9.jpg" 
    },
    { 
      id: 12, 
      organizerId: 2, 
      kategoriId: 2, 
      kotaId: 2, 
      judul: "Konferensi Digital Marketing Polines", 
      jenisEvent: "conference", 
      tipePlatform: "offline", 
      tipeHarga: "paid", 
      harga: 50000, 
      isEventPolines: true, 
      status: "published", 
      kuota: 120, 
      bannerUrl: "/uploads/banners/banner12.jpg", 
      syaratDanKetentuan: DEFAULT_TERMS, 
      deskripsi: "Konferensi riset taktis strategi pemasaran digital terapan bagi UMKM binaan Politeknik Negeri Semarang.", 
      detailLokasi: "Aula Jurusan Administrasi Bisnis, Polines", 
      tanggalMulai: futureDate(20), 
      tanggalSelesai: futureDate(20), 
      batasRegistrasi: futureDate(18), 
      namaKontak: "Business Dept Polines", 
      emailKontak: "bisnis@polines.ac.id", 
      teleponKontak: "024-7473424", 
      jumlahTayangan: 245, 
      namaPembicara: "Denny Santoso", 
      peranPembicara: "Digital Marketing Specialist", 
      fotoPembicaraUrl: "/uploads/speakers/speaker12.jpg" 
    },
    { 
      id: 14, 
      organizerId: 2, 
      kategoriId: 1, 
      kotaId: 2, 
      judul: "Konferensi Ethical Hacking Polines", 
      jenisEvent: "conference", 
      tipePlatform: "offline", 
      tipeHarga: "paid", 
      harga: 90000, 
      isEventPolines: true, 
      status: "published", 
      kuota: 80, 
      bannerUrl: "/uploads/banners/banner14.jpg", 
      syaratDanKetentuan: DEFAULT_TERMS, 
      deskripsi: "Konferensi dan sharing riset kerentanan siber untuk mewujudkan kedaulatan keamanan data nasional.", 
      detailLokasi: "Lab Keamanan Jaringan Gedung C, Polines", 
      tanggalMulai: futureDate(33), 
      tanggalSelesai: futureDate(34), 
      batasRegistrasi: futureDate(30), 
      namaKontak: "Hacking Club Polines", 
      emailKontak: "sec@polines.ac.id", 
      teleponKontak: "024-7473425", 
      jumlahTayangan: 312, 
      namaPembicara: "Jim Geovedi", 
      peranPembicara: "Ethical Hacking Specialist", 
      fotoPembicaraUrl: "/uploads/speakers/speaker14.jpg" 
    },
    { 
      id: 21, 
      organizerId: 2, 
      kategoriId: 1, 
      kotaId: 2, 
      judul: "Konferensi Nasional Teknologi Terapan Polines", 
      jenisEvent: "conference", 
      tipePlatform: "offline", 
      tipeHarga: "paid", 
      harga: 50000, 
      isEventPolines: true, 
      status: "published", 
      kuota: 150, 
      bannerUrl: "/uploads/banners/banner2.jpg", 
      syaratDanKetentuan: DEFAULT_TERMS + "\n9. Paper wajib orisinal dan belum dipublikasikan.", 
      deskripsi: "Konferensi nasional mempresentasikan hasil-hasil penelitian terapan terbaik dari perguruan tinggi vokasi di Indonesia.", 
      detailLokasi: "Gedung Pusat Informasi Polines, Semarang", 
      tanggalMulai: futureDate(42), 
      tanggalSelesai: futureDate(43), 
      batasRegistrasi: futureDate(38), 
      namaKontak: "P3M Polines", 
      emailKontak: "p3m@polines.ac.id", 
      teleponKontak: "024-7473426", 
      jumlahTayangan: 172, 
      namaPembicara: "Prof. Ir. Totok Prasetyo", 
      peranPembicara: "Director of Vocational Studies", 
      fotoPembicaraUrl: "/uploads/speakers/speaker2.jpg" 
    },
    { 
      id: 22, 
      organizerId: 2, 
      kategoriId: 4, 
      kotaId: 2, 
      judul: "Konferensi Riset Green Engineering & Energi Polines", 
      jenisEvent: "conference", 
      tipePlatform: "offline", 
      tipeHarga: "paid", 
      harga: 35000, 
      isEventPolines: true, 
      status: "published", 
      kuota: 100, 
      bannerUrl: "/uploads/banners/banner5.jpg", 
      syaratDanKetentuan: DEFAULT_TERMS, 
      deskripsi: "Konferensi ilmiah riset rekayasa hijau, manufaktur berkelanjutan, dan teknologi energi terbarukan di Polines.", 
      detailLokasi: "Ruang Seminar Jurusan Teknik Mesin Polines", 
      tanggalMulai: futureDate(48), 
      tanggalSelesai: futureDate(49), 
      batasRegistrasi: futureDate(44), 
      namaKontak: "Mechanical Dept Polines", 
      emailKontak: "mesin@polines.ac.id", 
      teleponKontak: "024-7473427", 
      jumlahTayangan: 145, 
      namaPembicara: "Dr. Eng. Masribah", 
      peranPembicara: "Renewable Energy Researcher", 
      fotoPembicaraUrl: "/uploads/speakers/speaker5.jpg" 
    },

    // === CONFERENCES + UMUM (6 Events) ===
    { 
      id: 2, 
      organizerId: 2, 
      kategoriId: 1, 
      kotaId: 4, 
      judul: "International Cybersecurity Conference 2026", 
      jenisEvent: "conference", 
      tipePlatform: "offline", 
      tipeHarga: "paid", 
      harga: 75000, 
      isEventPolines: false, 
      status: "published", 
      kuota: 50, 
      bannerUrl: "/uploads/banners/banner2.jpg", 
      syaratDanKetentuan: DEFAULT_TERMS + "\n9. Membawa laptop pribadi dengan spesifikasi minimal RAM 8GB.", 
      deskripsi: "Konferensi siber internasional intensif mengupas dasar keamanan digital dan ketahanan sistem cloud enterprise.", 
      detailLokasi: "Bandung Digital Valley, Jl. Gegerkalong Hilir", 
      tanggalMulai: futureDate(45), 
      tanggalSelesai: futureDate(46), 
      batasRegistrasi: futureDate(40), 
      namaKontak: "Tim CyberSec", 
      emailKontak: "cyber@event.id", 
      teleponKontak: "022-1234567", 
      jumlahTayangan: 198, 
      namaPembicara: "Sarah Connor", 
      peranPembicara: "Security Architect at Cyberdyne", 
      fotoPembicaraUrl: "/uploads/speakers/speaker2.jpg" 
    },
    { 
      id: 3, 
      organizerId: 2, 
      kategoriId: 5, 
      kotaId: 11, 
      judul: "Konferensi Kesehatan Digital Indonesia", 
      jenisEvent: "conference", 
      tipePlatform: "online", 
      tipeHarga: "paid", 
      harga: 100000, 
      isEventPolines: false, 
      status: "published", 
      kuota: 500, 
      bannerUrl: "/uploads/banners/banner3.jpg", 
      syaratDanKetentuan: DEFAULT_TERMS + "\n9. Link Zoom akan dikirimkan H-1 melalui email terdaftar.", 
      deskripsi: "Konferensi tahunan membahas pilar-pilar penting transformasi sistem rekam medis dan kesehatan digital.", 
      detailLokasi: "Grand Ballroom Kempinski, Jakarta Pusat", 
      tanggalMulai: futureDate(60), 
      tanggalSelesai: futureDate(61), 
      batasRegistrasi: futureDate(55), 
      namaKontak: "Sekretariat KKDI", 
      emailKontak: "info@kkdi.id", 
      teleponKontak: "021-5551234", 
      jumlahTayangan: 320, 
      linkEksternal: SEED.DEFAULT_TICKET_URL, 
      namaPembicara: "dr. Budi Santoso, Sp.KO", 
      peranPembicara: "Chief Medical Officer", 
      fotoPembicaraUrl: "/uploads/speakers/speaker3.jpg" 
    },
    { 
      id: 8, 
      organizerId: 2, 
      kategoriId: 2, 
      kotaId: 3, 
      judul: "Career Conference 2026", 
      jenisEvent: "conference", 
      tipePlatform: "offline", 
      tipeHarga: "free", 
      harga: 0, 
      isEventPolines: false, 
      status: "published", 
      kuota: 2000, 
      bannerUrl: "/uploads/banners/banner8.jpg", 
      syaratDanKetentuan: DEFAULT_TERMS, 
      deskripsi: "Konferensi karir terakreditasi nasional menghubungkan akademisi dengan narasumber andal berbagai industri global.", 
      detailLokasi: "Grand City Convention, Surabaya", 
      tanggalMulai: futureDate(40), 
      tanggalSelesai: futureDate(42), 
      batasRegistrasi: futureDate(38), 
      namaKontak: "Panitia Career", 
      emailKontak: "career@surabaya.id", 
      teleponKontak: "031-8888999", 
      jumlahTayangan: 890, 
      namaPembicara: "Maudy Ayunda", 
      peranPembicara: "Chief Career Officer at Zenius", 
      fotoPembicaraUrl: "/uploads/speakers/speaker8.jpg" 
    },
    { 
      id: 18, 
      organizerId: 2, 
      kategoriId: 7, 
      kotaId: 1, 
      judul: "Konferensi Musik Tradisional Aceh", 
      jenisEvent: "conference", 
      tipePlatform: "offline", 
      tipeHarga: "paid", 
      harga: 35000, 
      isEventPolines: false, 
      status: "published", 
      kuota: 500, 
      bannerUrl: "/uploads/banners/banner18.jpg", 
      syaratDanKetentuan: DEFAULT_TERMS, 
      deskripsi: "Konferensi riset ilmiah membedah struktur ritmik, sejarah perkembangan, dan orisinalitas alat musik adat Aceh.", 
      detailLokasi: "Auditorium Unsyiah, Banda Aceh", 
      tanggalMulai: futureDate(80), 
      tanggalSelesai: futureDate(81), 
      batasRegistrasi: futureDate(75), 
      namaKontak: "Musik Unsyiah", 
      emailKontak: "musik@unsyiah.ac.id", 
      teleponKontak: "0651-7551174", 
      jumlahTayangan: 120, 
      namaPembicara: "Rafly Kande", 
      peranPembicara: "Aceh Musician & Expert", 
      fotoPembicaraUrl: "/uploads/speakers/speaker18.jpg" 
    },
    { 
      id: 23, 
      organizerId: 2, 
      kategoriId: 1, 
      kotaId: 12, 
      judul: "International Web Development Conference 2026", 
      jenisEvent: "conference", 
      tipePlatform: "offline", 
      tipeHarga: "paid", 
      harga: 150000, 
      isEventPolines: false, 
      status: "published", 
      kuota: 400, 
      bannerUrl: "/uploads/banners/banner9.jpg", 
      syaratDanKetentuan: DEFAULT_TERMS, 
      deskripsi: "Konferensi riset inovasi dan teknik termutakhir seputar Next.js, React, compiler web, dan masa depan edge computing.", 
      detailLokasi: "Menara BCA Grand Indonesia, Jakarta", 
      tanggalMulai: futureDate(38), 
      tanggalSelesai: futureDate(39), 
      batasRegistrasi: futureDate(35), 
      namaKontak: "Indo Web Community", 
      emailKontak: "info@webdevconf.id", 
      teleponKontak: "021-99887766", 
      jumlahTayangan: 310, 
      namaPembicara: "Dan Abramov", 
      peranPembicara: "React Core Team Member", 
      fotoPembicaraUrl: "/uploads/speakers/speaker9.jpg" 
    },
    { 
      id: 24, 
      organizerId: 2, 
      kategoriId: 2, 
      kotaId: 3, 
      judul: "Asia-Pacific Business Strategy Conference", 
      jenisEvent: "conference", 
      tipePlatform: "offline", 
      tipeHarga: "paid", 
      harga: 200000, 
      isEventPolines: false, 
      status: "published", 
      kuota: 300, 
      bannerUrl: "/uploads/banners/banner12.jpg", 
      syaratDanKetentuan: DEFAULT_TERMS, 
      deskripsi: "Rapat riset dan kajian strategis model bisnis adaptif di pasar Asia-Pasifik menghadapi disrupsi teknologi berkelanjutan.", 
      detailLokasi: "Shangri-La Hotel, Surabaya", 
      tanggalMulai: futureDate(54), 
      tanggalSelesai: futureDate(56), 
      batasRegistrasi: futureDate(50), 
      namaKontak: "AP Business Board", 
      emailKontak: "ap@strategyboard.org", 
      teleponKontak: "031-77665544", 
      jumlahTayangan: 180, 
      namaPembicara: "Eric Ries", 
      peranPembicara: "Author of The Lean Startup", 
      fotoPembicaraUrl: "/uploads/speakers/speaker12.jpg" 
    }
  ] as const;

  for (const e of events) {
    const s = slug(e.judul);
    const isPaid = e.tipeHarga === "paid";
    
    const paymentInfo = isPaid ? {
      namaBank: "Bank Mandiri",
      nomorRekening: "132-000-1234-567",
      pemilikRekening: "Panitia POLIVENTS",
      namaBankAlternatif: "E-Wallet (Dana / ShopeePay)",
      nomorRekeningAlternatif: "0812-3456-7890",
      pemilikRekeningAlternatif: "POLIVENTS Internal"
    } : {
      namaBank: null,
      nomorRekening: null,
      pemilikRekening: null,
      namaBankAlternatif: null,
      nomorRekeningAlternatif: null,
      pemilikRekeningAlternatif: null
    };

    await db.insert(event).values({
      ...e,
      ...paymentInfo,
      slug: s,
      status: e.status as "published" | "pending" | "rejected", 
      jenisEvent: e.jenisEvent as "seminar" | "conference",
      tipePlatform: e.tipePlatform as "offline" | "online" | "hybrid",
      tipeHarga: e.tipeHarga as "free" | "paid",
      satuAkunSatuTransaksi: false,
      hasilScraping: false,
      dibuatPada: new Date(),
    } as typeof event.$inferInsert).onConflictDoUpdate({
      target: event.slug,
      set: { 
        judul: e.judul, 
        status: e.status as "published" | "pending" | "rejected", 
        harga: e.harga, 
        bannerUrl: e.bannerUrl,
        syaratDanKetentuan: e.syaratDanKetentuan,
        jenisEvent: e.jenisEvent as "seminar" | "conference",
        kategoriId: e.kategoriId,
        jumlahTayangan: e.jumlahTayangan, 
        namaPembicara: e.namaPembicara,
        peranPembicara: e.peranPembicara,
        fotoPembicaraUrl: e.fotoPembicaraUrl,
        linkEksternal: "linkEksternal" in e ? e.linkEksternal : null,
        namaBank: paymentInfo.namaBank,
        nomorRekening: paymentInfo.nomorRekening,
        pemilikRekening: paymentInfo.pemilikRekening,
        namaBankAlternatif: paymentInfo.namaBankAlternatif,
        nomorRekeningAlternatif: paymentInfo.nomorRekeningAlternatif,
        pemilikRekeningAlternatif: paymentInfo.pemilikRekeningAlternatif,
        dibuatPada: new Date() 
      }
    });
  }

  console.log("✅ Redesigned 24 perfectly balanced events successfully seeded!");
}
