import { db } from "./index";
import { event } from "./schema";

function slug(text: string) {
  return text.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
}

function futureDate(daysFromNow: number) {
  return new Date(Date.now() + daysFromNow * 86400000);
}

const DEFAULT_TERMS = `1. Peserta wajib melakukan registrasi melalui website SISC.
2. Peserta diharapkan hadir 15 menit sebelum acara dimulai untuk proses check-in.
3. Wajib menunjukkan E-Ticket (QR Code) saat memasuki area acara.
4. Menggunakan pakaian yang rapi, sopan, dan sesuai dengan tema acara.
5. Peserta wajib menjaga ketertiban dan kebersihan selama acara berlangsung.
6. Dilarang membawa senjata tajam, obat-obatan terlarang, atau benda berbahaya lainnya.
7. Panitia berhak membatalkan keikutsertaan jika peserta melanggar aturan yang ditetapkan.
8. Keputusan panitia bersifat mutlak dan tidak dapat diganggu gugat.`;

export async function seedEvents() {
  console.log("🚀 Seeding 18 events with Banners & Terms...");

  const events = [
    { id:1, organizerId:2, kategoriId:1, kotaId:2, judul:"Seminar Nasional AI & Big Data 2026", jenisEvent:"seminar", tipePlatform:"offline", tipeHarga:"free", harga:0, isEventPolines:true, status:"published", kuota:200, bannerUrl:"/uploads/banners/banner1.jpg", syaratDanKetentuan: DEFAULT_TERMS, deskripsi:"Seminar nasional membahas perkembangan AI dan Big Data di Indonesia.", detailLokasi:"Gedung Kuliah Bersama, Polines, Semarang", tanggalMulai:futureDate(30), tanggalSelesai:futureDate(30), batasRegistrasi:futureDate(28), namaKontak:"Panitia AI Polines", emailKontak:"ai@polines.ac.id", teleponKontak:"024-7473417", jumlahTayangan:150, namaPembicara: "Dr. Eng. Ahmad Zaki", peranPembicara: "AI Researcher at Google", fotoPembicaraUrl: "/uploads/speakers/speaker1.jpg" },
    { id:2, organizerId:2, kategoriId:1, kotaId:4, judul:"Workshop Cybersecurity Fundamentals", jenisEvent:"conference", tipePlatform:"offline", tipeHarga:"paid", harga:75000, isEventPolines:false, status:"published", kuota:50, bannerUrl:"/uploads/banners/banner2.jpg", syaratDanKetentuan: DEFAULT_TERMS + "\n9. Membawa laptop pribadi dengan spesifikasi minimal RAM 8GB.", deskripsi:"Konferensi intensif mempelajari dasar-dasar Keamanan Siber.", detailLokasi:"Bandung Digital Valley, Jl. Gegerkalong Hilir", tanggalMulai:futureDate(45), tanggalSelesai:futureDate(46), batasRegistrasi:futureDate(40), namaKontak:"Tim CyberSec", emailKontak:"cyber@event.id", teleponKontak:"022-1234567", jumlahTayangan:89, namaPembicara: "Sarah Connor", peranPembicara: "Security Architect", fotoPembicaraUrl: "/uploads/speakers/speaker2.jpg" },
    { id:3, organizerId:2, kategoriId:5, kotaId:11, judul:"Konferensi Kesehatan Digital Indonesia", jenisEvent:"conference", tipePlatform:"online", tipeHarga:"paid", harga:100000, isEventPolines:false, status:"published", kuota:500, bannerUrl:"/uploads/banners/banner3.jpg", syaratDanKetentuan: DEFAULT_TERMS + "\n9. Link Zoom akan dikirimkan H-1 melalui email terdaftar.", deskripsi:"Konferensi tahunan membahas transformasi digital di sektor kesehatan.", detailLokasi:null, tanggalMulai:futureDate(60), tanggalSelesai:futureDate(61), batasRegistrasi:futureDate(55), namaKontak:"Sekretariat KKDI", emailKontak:"info@kkdi.id", teleponKontak:"021-5551234", jumlahTayangan:320, linkEksternal:"https://loket.com/", namaPembicara: "dr. Budi Santoso, Sp.KO", peranPembicara: "Chief Medical Officer", fotoPembicaraUrl: "/uploads/speakers/speaker3.jpg" },
    { id:4, organizerId:2, kategoriId:2, kotaId:null, judul:"Webinar Kewirausahaan Muda", jenisEvent:"seminar", tipePlatform:"online", tipeHarga:"free", harga:0, isEventPolines:false, status:"published", kuota:1000, bannerUrl:"/uploads/banners/banner4.jpg", syaratDanKetentuan: DEFAULT_TERMS, deskripsi:"Webinar gratis bagi mahasiswa yang ingin memulai bisnis.", detailLokasi:null, tanggalMulai:futureDate(14), tanggalSelesai:futureDate(14), batasRegistrasi:futureDate(13), namaKontak:"Komunitas Wirausaha", emailKontak:"wirausaha@gmail.com", teleponKontak:"081234000111", jumlahTayangan:567, linkEksternal:"https://loket.com/", namaPembicara: "Gibran Rakabuming", peranPembicara: "Entrepreneur & Mentor", fotoPembicaraUrl: "/uploads/speakers/speaker4.jpg" },
    { id:5, organizerId:2, kategoriId:1, kotaId:2, judul:"Konferensi Smart Campus Polines", jenisEvent:"conference", tipePlatform:"offline", tipeHarga:"free", harga:0, isEventPolines:true, status:"published", kuota:100, bannerUrl:"/uploads/banners/banner5.jpg", syaratDanKetentuan: DEFAULT_TERMS, deskripsi:"Konferensi mengenai solusi teknologi kampus cerdas.", detailLokasi:"Lab Komputer Gedung A, Polines", tanggalMulai:futureDate(21), tanggalSelesai:futureDate(23), batasRegistrasi:futureDate(18), namaKontak:"BEM Polines", emailKontak:"bem@polines.ac.id", teleponKontak:"024-7473418", jumlahTayangan:234, namaPembicara: "Prof. Sujatmiko", peranPembicara: "IT Infrastructure Lead", fotoPembicaraUrl: "/uploads/speakers/speaker5.jpg" },
    { id:6, organizerId:2, kategoriId:4, kotaId:5, judul:"Seminar Riset Pendidikan Inklusif", jenisEvent:"seminar", tipePlatform:"hybrid", tipeHarga:"paid", harga:50000, isEventPolines:false, status:"pending", kuota:150, bannerUrl:"/uploads/banners/banner6.jpg", syaratDanKetentuan: DEFAULT_TERMS, deskripsi:"Membahas strategi riset pendidikan inklusif di era digital.", detailLokasi:"Auditorium UGM, Yogyakarta", tanggalMulai:futureDate(35), tanggalSelesai:futureDate(35), batasRegistrasi:futureDate(30), namaKontak:"Forum Pendidikan", emailKontak:"pendidikan@ugm.ac.id", teleponKontak:"0274-513096", jumlahTayangan:45, namaPembicara: "Anies Baswedan", peranPembicara: "Education Consultant", fotoPembicaraUrl: "/uploads/speakers/speaker6.jpg" },
    { id:7, organizerId:2, kategoriId:7, kotaId:5, judul:"Seminar Seni & Budaya Nusantara", jenisEvent:"seminar", tipePlatform:"offline", tipeHarga:"paid", harga:25000, isEventPolines:false, status:"published", kuota:300, bannerUrl:"/uploads/banners/banner7.jpg", syaratDanKetentuan: DEFAULT_TERMS, deskripsi:"Diskusi panel tentang pelestarian budaya tradisional.", detailLokasi:"Taman Budaya Yogyakarta", tanggalMulai:futureDate(50), tanggalSelesai:futureDate(52), batasRegistrasi:futureDate(48), namaKontak:"DKY Yogyakarta", emailKontak:"senibudaya@jogja.go.id", teleponKontak:"0274-523512", jumlahTayangan:178, namaPembicara: "Didik Nini Thowok", peranPembicara: "Cultural Expert", fotoPembicaraUrl: "/uploads/speakers/speaker7.jpg" },
    { id:8, organizerId:2, kategoriId:2, kotaId:3, judul:"Career Conference 2026", jenisEvent:"conference", tipePlatform:"offline", tipeHarga:"free", harga:0, isEventPolines:false, status:"published", kuota:2000, bannerUrl:"/uploads/banners/banner8.jpg", syaratDanKetentuan: DEFAULT_TERMS, deskripsi:"Konferensi karir terbesar dengan berbagai narasumber industri.", detailLokasi:"Grand City Convention, Surabaya", tanggalMulai:futureDate(40), tanggalSelesai:futureDate(42), batasRegistrasi:futureDate(38), namaKontak:"Panitia Career", emailKontak:"career@surabaya.id", teleponKontak:"031-8888999", jumlahTayangan:890, namaPembicara: "Maudy Ayunda", peranPembicara: "Chief Career Officer", fotoPembicaraUrl: "/uploads/speakers/speaker8.jpg" },
    { id:9, organizerId:2, kategoriId:4, kotaId:12, judul:"Konferensi Sains & Teknologi Python", jenisEvent:"conference", tipePlatform:"offline", tipeHarga:"paid", harga:150000, isEventPolines:false, status:"published", kuota:40, bannerUrl:"/uploads/banners/banner9.jpg", syaratDanKetentuan: DEFAULT_TERMS, deskripsi:"Pertemuan peneliti sains menggunakan bahasa pemrograman Python.", detailLokasi:"WeWork Revenue Tower, Jakarta Selatan", tanggalMulai:futureDate(28), tanggalSelesai:futureDate(29), batasRegistrasi:futureDate(25), namaKontak:"Data Science Community", emailKontak:"hello@data.dev", teleponKontak:"021-5556789", jumlahTayangan:112, namaPembicara: "Guido van Rossum", peranPembicara: "Python Creator", fotoPembicaraUrl: "/uploads/speakers/speaker9.jpg" },
    { id:10, organizerId:2, kategoriId:8, kotaId:10, judul:"Seminar Gaya Hidup Berkelanjutan", jenisEvent:"seminar", tipePlatform:"hybrid", tipeHarga:"free", harga:0, isEventPolines:false, status:"published", kuota:200, bannerUrl:"/uploads/banners/banner10.jpg", syaratDanKetentuan: DEFAULT_TERMS, deskripsi:"Diskusi tentang gaya hidup ramah lingkungan dan zero waste.", detailLokasi:"Bali Nusa Dua Convention Center", tanggalMulai:futureDate(55), tanggalSelesai:futureDate(55), batasRegistrasi:futureDate(50), namaKontak:"Green Foundation", emailKontak:"green@bali.org", teleponKontak:"0361-771234", jumlahTayangan:267, namaPembicara: "Nadya Hutagalung", peranPembicara: "Environmental Activist", fotoPembicaraUrl: "/uploads/speakers/speaker10.jpg" },
    { id:11, organizerId:2, kategoriId:9, kotaId:2, judul:"Seminar Manajemen E-Sports Polines", jenisEvent:"seminar", tipePlatform:"offline", tipeHarga:"paid", harga:30000, isEventPolines:true, status:"published", kuota:64, bannerUrl:"/uploads/banners/banner11.jpg", syaratDanKetentuan: DEFAULT_TERMS, deskripsi:"Seminar mengenai industri dan manajemen E-Sports di kampus.", detailLokasi:"GOR Polines, Semarang", tanggalMulai:futureDate(10), tanggalSelesai:futureDate(11), batasRegistrasi:futureDate(7), namaKontak:"UKM E-Sports", emailKontak:"esports@polines.ac.id", teleponKontak:"024-7473419", jumlahTayangan:445, namaPembicara: "Jess No Limit", peranPembicara: "E-Sports Professional", fotoPembicaraUrl: "/uploads/speakers/speaker11.jpg" },
    { id:12, organizerId:2, kategoriId:2, kotaId:6, judul:"Konferensi Digital Marketing UMKM", jenisEvent:"conference", tipePlatform:"online", tipeHarga:"paid", harga:85000, isEventPolines:false, status:"published", kuota:100, bannerUrl:"/uploads/banners/banner12.jpg", syaratDanKetentuan: DEFAULT_TERMS, deskripsi:"Strategi konferensi pemasaran digital untuk skala kecil dan menengah.", detailLokasi:null, tanggalMulai:futureDate(20), tanggalSelesai:futureDate(20), batasRegistrasi:futureDate(18), namaKontak:"DigiMarketing", emailKontak:"digimark@medan.id", teleponKontak:"061-4521234", jumlahTayangan:198, linkEksternal:"https://loket.com/", namaPembicara: "Denny Santoso", peranPembicara: "Digital Marketing Specialist", fotoPembicaraUrl: "/uploads/speakers/speaker12.jpg" },
    { id:13, organizerId:2, kategoriId:4, kotaId:7, judul:"Seminar Pendidikan Vokasi Nasional", jenisEvent:"seminar", tipePlatform:"offline", tipeHarga:"free", harga:0, isEventPolines:false, status:"pending", kuota:300, bannerUrl:"/uploads/banners/banner13.jpg", syaratDanKetentuan: DEFAULT_TERMS, deskripsi:"Forum diskusi untuk meningkatkan kualitas pendidikan vokasi.", detailLokasi:"Hotel Claro Makassar", tanggalMulai:futureDate(70), tanggalSelesai:futureDate(72), batasRegistrasi:futureDate(65), namaKontak:"Forum Vokasi", emailKontak:"vokasi@makassar.id", teleponKontak:"0411-3621234", jumlahTayangan:56, namaPembicara: "Nadiem Makarim", peranPembicara: "Minister of Education", fotoPembicaraUrl: "/uploads/speakers/speaker13.jpg" },
    { id:14, organizerId:2, kategoriId:1, kotaId:9, judul:"Konferensi Ethical Hacking Indonesia", jenisEvent:"conference", tipePlatform:"hybrid", tipeHarga:"paid", harga:120000, isEventPolines:false, status:"published", kuota:35, bannerUrl:"/uploads/banners/banner14.jpg", syaratDanKetentuan: DEFAULT_TERMS, deskripsi:"Konferensi keamanan siber dengan fokus pada peretasan etis.", detailLokasi:"Swiss-Belhotel Balikpapan", tanggalMulai:futureDate(33), tanggalSelesai:futureDate(34), batasRegistrasi:futureDate(30), namaKontak:"CyberSec Indo", emailKontak:"info@cybersec.id", teleponKontak:"0542-7351234", jumlahTayangan:167, namaPembicara: "Jim Geovedi", peranPembicara: "Hacking Specialist", fotoPembicaraUrl: "/uploads/speakers/speaker14.jpg" },
    { id:15, organizerId:2, kategoriId:5, kotaId:8, judul:"Seminar Kesehatan Masyarakat Palembang", jenisEvent:"seminar", tipePlatform:"offline", tipeHarga:"free", harga:0, isEventPolines:false, status:"published", kuota:50, bannerUrl:"/uploads/banners/banner15.jpg", syaratDanKetentuan: DEFAULT_TERMS, deskripsi:"Edukasi kesehatan gratis untuk masyarakat umum.", detailLokasi:"Puskesmas Kertapati, Palembang", tanggalMulai:futureDate(15), tanggalSelesai:futureDate(15), batasRegistrasi:futureDate(12), namaKontak:"Kesehatan Daerah", emailKontak:"kes@palembang.go.id", teleponKontak:"0711-3551234", jumlahTayangan:78, namaPembicara: "dr. Tirta", peranPembicara: "Health Influencer", fotoPembicaraUrl: "/uploads/speakers/speaker15.jpg" },
    { id:16, organizerId:2, kategoriId:3, kotaId:4, judul:"Seminar Seni Digital & UI/UX", jenisEvent:"seminar", tipePlatform:"offline", tipeHarga:"paid", harga:40000, isEventPolines:false, status:"published", kuota:200, bannerUrl:"/uploads/banners/banner16.jpg", syaratDanKetentuan: DEFAULT_TERMS, deskripsi:"Integrasi seni digital dalam alur kerja desain antarmuka.", detailLokasi:"Gedung Sate Creative Hub, Bandung", tanggalMulai:futureDate(25), tanggalSelesai:futureDate(27), batasRegistrasi:futureDate(22), namaKontak:"Creative Hub", emailKontak:"creative@bandung.id", teleponKontak:"022-4201234", jumlahTayangan:234, namaPembicara: "Rio Purba", peranPembicara: "UI/UX Designer", fotoPembicaraUrl: "/uploads/speakers/speaker16.jpg" },
    { id:17, organizerId:2, kategoriId:1, kotaId:null, judul:"Seminar Machine Learning for Beginners", jenisEvent:"seminar", tipePlatform:"online", tipeHarga:"free", harga:0, isEventPolines:false, status:"published", kuota:500, bannerUrl:"/uploads/banners/banner17.jpg", syaratDanKetentuan: DEFAULT_TERMS, deskripsi:"Pengenalan praktis machine learning untuk mahasiswa.", detailLokasi:null, tanggalMulai:futureDate(7), tanggalSelesai:futureDate(7), batasRegistrasi:futureDate(6), namaKontak:"ML Hub", emailKontak:"ml@dev.id", teleponKontak:"081999888777", jumlahTayangan:678, linkEksternal:"https://loket.com/", namaPembicara: "Andrew Ng", peranPembicara: "AI Professor", fotoPembicaraUrl: "/uploads/speakers/speaker17.jpg" },
    { id:18, organizerId:2, kategoriId:7, kotaId:1, judul:"Konferensi Musik Tradisional Aceh", jenisEvent:"conference", tipePlatform:"offline", tipeHarga:"paid", harga:35000, isEventPolines:false, status:"published", kuota:500, bannerUrl:"/uploads/banners/banner18.jpg", syaratDanKetentuan: DEFAULT_TERMS, deskripsi:"Konferensi ilmiah membahas sejarah and perkembangan musik Aceh.", detailLokasi:"Auditorium Unsyiah, Banda Aceh", tanggalMulai:futureDate(80), tanggalSelesai:futureDate(81), batasRegistrasi:futureDate(75), namaKontak:"Musik Unsyiah", emailKontak:"musik@unsyiah.ac.id", teleponKontak:"0651-7551174", jumlahTayangan:12, namaPembicara: "Rafly Kande", peranPembicara: " Aceh Musician", fotoPembicaraUrl: "/uploads/speakers/speaker18.jpg" },
  ] as const;

  for (const e of events) {
    const s = slug(e.judul);
    await db.insert(event).values({
      ...e,
      slug: s,
      status: e.status as "published" | "pending" | "rejected", 
      jenisEvent: e.jenisEvent as "seminar" | "conference",
      tipePlatform: e.tipePlatform as "offline" | "online" | "hybrid",
      tipeHarga: e.tipeHarga as "free" | "paid",
      satuAkunSatuTransaksi: false,
      hasilScraping: false,
      dibuatPada: new Date(),
    } as typeof event.$inferInsert).onConflictDoUpdate({
      target: event.slug,
      set: { 
        judul: e.judul, 
        status: e.status as "published" | "pending" | "rejected", 
        harga: e.harga, 
        bannerUrl: e.bannerUrl,
        syaratDanKetentuan: e.syaratDanKetentuan,
        jenisEvent: e.jenisEvent as "seminar" | "conference",
        kategoriId: e.kategoriId,
        jumlahTayangan: e.jumlahTayangan, 
        namaPembicara: e.namaPembicara,
        peranPembicara: e.peranPembicara,
        fotoPembicaraUrl: e.fotoPembicaraUrl,
        linkEksternal: "linkEksternal" in e ? e.linkEksternal : null,
        dibuatPada: new Date() 
      }
    });
  }

  console.log("✅ 18 events with Banners & Terms seeded!");
}

